version: "3.9"

services:
  backend:
    build: .
    container_name: ai-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_DATABASE=AI_BACKEND
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
