version: "3.9"

services:
  backend:
    build: .
    container_name: ai-backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_DATABASE=AI_BACKEND
      - OPENAI_API_KEY=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
      - PINECONE_API_KEY=pcsk_51HNkK_FQQjAb3cSphGWmw8beAzE3XYzXGPnbauJ6KZ6EWuEY1exdnEMQA84TMz7sBX2WT
      - PINECONE_ENVIRONMENT=us-east-1
